_target_: wildfire_forecasting.datamodules.greecefire_datamodule.FireDSDataModule

# dataset_root: /home/hugosoto/Work/git/ine-on-fire/model/data/sample_paper/
dataset_root: /media/hugosoto/Elements/dataton_do_2024/datasets_grl/
batch_size: 256
num_workers: 16
pin_memory: False
access_mode: 'temporal'
problem_class: 'classification'
nan_fill: -1.0
sel_dynamic_features: ${sel_dynamic_features}
sel_static_features: ${sel_static_features}
prefetch_factor : 2
persistent_workers : False
